name: revove
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - Django>=6.0,<6.1
      - djangorestframework>=3.15,<3.16
      - django-filter>=24.3,<24.4
      - django-cors-headers>=4.4,<4.5
      - requests>=2.32,<2.33
      - python-dotenv>=1.0,<1.1
      - psycopg2-binary>=2.9,<3.0
      - gunicorn>=22.0,<22.1
      - numpy>=1.26,<2.0
      - sentence-transformers>=3.1,<3.2
